### ISSUE TITLE
Print a value to a sertain position

### ISSUE THREAD

**Issue by sns5400** [noah1510/LedController#15]
Hello,
I try your library with the idea to built a 5 axis machine display. using esp32dev as processor. The axis are selected with the cs pin but the value can be positive, negative and the decimal place on a certain position.

Is that possible ?

**Comment by noah1510** [comment]
It should be possible.
Do you want to use a Led Matrix or a 7 segment display, since they way the need to be handled is totally different?

For more details ask on [gitter](https://gitter.im/LedControllerN/helpdesk) since the issues are intended for issues and feature requests.

**Comment by sns5400** [comment]
i prefer the 8 x 7 segment modules there are cheap and practice in use
