### ISSUE TITLE
error compail at arduino uno

### ISSUE THREAD

**Issue by gunaone** [noah1510/LedController#17]
version 1.7.2
`In file included from LCDemo7Segment.ino:3:0:
C:\Users\gunaon3\Documents\Arduino\libraries\LedController\src/LedController.hpp:9:7: error: expected nested-name-specifier before 'ByteBlock'
 using ByteBlock = byte[8];
       ^
C:\Users\gunaon3\Documents\Arduino\libraries\LedController\src/LedController.hpp:9:7: error: 'ByteBlock' has not been declared
C:\Users\gunaon3\Documents\Arduino\libraries\LedController\src/LedController.hpp:9:17: error: expected ';' before '=' token
 using ByteBlock = byte[8];
                 ^
C:\Users\gunaon3\Documents\Arduino\libraries\LedController\src/LedController.hpp:9:17: error: expected unqualified-id before '=' token
In file included from C:\Users\gunaon3\Documents\Arduino\libraries\LedController\src/LedController.hpp:29:0,
                 from LCDemo7Segment.ino:3:
C:\Users\gunaon3\Documents\Arduino\libraries\LedController\src/LedController_config.hpp:74:30: error: 'nullptr' was not declared in this scope
   unsigned int *row_SPI_CS = nullptr;
                              ^
C:\Users\gunaon3\Documents\Arduino\libraries\LedController\src/LedController_config.hpp: In static member function 'static bool controller_configuration::isValidConfig(const controller_configuration&)':
C:\Users\gunaon3\Documents\Arduino\libraries\LedController\src/LedController_config.hpp:93:48: error: 'nullptr' was not declared in this scope
     if (conf.SPI_CS == 0 && conf.row_SPI_CS == nullptr) {
                                                ^
C:\Users\gunaon3\Documents\Arduino\libraries\LedController\src/LedController_config.hpp:98:28: error: 'nullptr' was not declared in this scope
     if (conf.row_SPI_CS != nullptr &&
                            ^
In file included from LCDemo7Segment.ino:3:0:
C:\Users\gunaon3\Documents\Arduino\libraries\LedController\src/LedController.hpp: At global scope:
C:\Users\gunaon3\Documents\Arduino\libraries\LedController\src/LedController.hpp:44:3: error: 'ByteBlock' does not name a type
   ByteBlock *LedStates = nullptr;
   ^
C:\Users\gunaon3\Documents\Arduino\libraries\LedController\src/LedController.hpp:198:52: error: 'ByteBlock' has not been declared
   void displayOnSegment(unsigned int segmentindex, ByteBlock data);
                                                    ^
C:\Users\gunaon3\Documents\Arduino\libraries\LedController\src/LedController.hpp:206:50: error: 'ByteBlock' has not been declared
   void getSegmentData(unsigned int segmentindex, ByteBlock *resultLocation);
                                                  ^
C:\Users\gunaon3\Documents\Arduino\libraries\LedController\src/LedController.hpp:444:20: error: 'ByteBlock' has not been declared
   void makeColumns(ByteBlock rowArray, ByteBlock *columnArray);
                    ^
C:\Users\gunaon3\Documents\Arduino\libraries\LedController\src/LedController.hpp:444:40: error: 'ByteBlock' has not been declared
   void makeColumns(ByteBlock rowArray, ByteBlock *columnArray);
                                        ^
C:\Users\gunaon3\Documents\Arduino\libraries\LedController\src/LedController.hpp:452:16: error: 'ByteBlock' has not been declared
   void reverse(ByteBlock input, ByteBlock *reversedInput);
                ^
C:\Users\gunaon3\Documents\Arduino\libraries\LedController\src/LedController.hpp:452:33: error: 'ByteBlock' has not been declared
   void reverse(ByteBlock input, ByteBlock *reversedInput);
                                 ^
C:\Users\gunaon3\Documents\Arduino\libraries\LedController\src/LedController.hpp:460:18: error: 'ByteBlock' has not been declared
   void rotate180(ByteBlock input, ByteBlock *rotatedInput);
                  ^
C:\Users\gunaon3\Documents\Arduino\libraries\LedController\src/LedController.hpp:460:35: error: 'ByteBlock' has not been declared
   void rotate180(ByteBlock input, ByteBlock *rotatedInput);
                                   ^
C:\Users\gunaon3\Documents\Arduino\libraries\LedController\src/LedController.hpp:62:19: error: 'nullptr' was not declared in this scope
   byte *spidata = nullptr;
                   ^
C:\Users\gunaon3\Documents\Arduino\libraries\LedController\src/LedController.hpp:82:20: error: 'nullptr' was not declared in this scope
   byte *emptyRow = nullptr;
                    ^
Multiple libraries were found for "SPI.h"
 Used: C:\Users\gunaon3\Documents\Arduino\libraries\SPI_master
 Not used: F:\APLIKASI\ELEKTRONIKA\ARDUINO\arduino-1.6.5-r5\hardware\arduino\avr\libraries\SPI
Error compiling.`

**Comment by noah1510** [comment]
Can provide some details?
What board are you using?
Which version of the led controller?
Which version of the arduino IDE?
What operating system?
Have you tryed anything to get it working if yes what?

**Comment by gunaone** [comment]
arduino uno at328
version 1.7.2
IDE 1.6.5  it not working
IDE 1.6.10 it's working
windows 10

thanks @noah1510
