### ISSUE TITLE
Add function to get LED state?

### ISSUE THREAD

**Issue by LennartHennigs** [noah1510/LedController#4]
Hey 
is there a way to read the state of an LED? 
I'd really like to have a function like this:

`boolean getLed(unsigned int segmentNumber, unsigned int row, unsigned int  column)`

(This would reduce the need for me store the state in an array. And since I am using 20 8x8 matrixes I am running low on variable storage memory :-) )

Cheers
l.

**Comment by noah1510** [comment]
would it be enough for you to simply retrieve a single row because that is way faster and if you need a specific value you can get that?

**Comment by LennartHennigs** [comment]
Sure. just return a byte and in check the bits...

**Comment by noah1510** [comment]
Should work now just use the getRow function, it will be released with next version.

**Comment by LennartHennigs** [comment]
Thx. Appreciate it.

**Comment by noah1510** [comment]
release 1.6.1 now includes the [getRow](https://noah1510.github.io/LedController/d9/def/class_led_controller.html#a3ecd47a8ae3ea19e61b6d9599a977065) function so I will close this issue.
In case you want more functions to (e.g. getSegment or getLed) then open a seperate issue or pull request I plan on adding this in the future.
